@startuml
!theme plain

title Процесс управления автомобилями (Менеджер)

start
:Есть новые бронирования?;

if (есть бронирования) then (да)
  if (Клиент подтверждает бронирование?) then (да)
    :Оформить продажу;
    :Смена статуса автомобиля\nна "продан";
  else (нет)
    :Отмена брони;
    :Смена статуса автомобиля\nна "на складе";
  endif
else (нет)
  :Заполнить данные о новом автомобиле;
  :Добавить автомобиль;
endif

stop

@enduml