@startuml
!theme plain

title Процесс бронирования (Покупатель)

start
:Выбор автомобиля в каталоге;

if (Статус автомобиля "на складе"?) then (да)
  :Ввод контактных данных;
  :Подтверждение бронирования;
  :Изменение статуса автомобиля\nна "забронирован";
else (нет)
  :Сообщение: "недоступно";
endif

stop

@enduml